// import '/imports/api/activations/methods';
// import '/imports/api/activations/server/publications';
// import '/imports/api/bells/server/publications';
import '../imports/api/easy_events/server';
// import '/imports/api/fields/server/publications';
import '../imports/api/intentions/server/publications';
// import '../imports/api/likes/methods';
import '../imports/api/likes/server/publications';
// import '/imports/api/messages/server/publications';
import '../imports/api/rsvp/methods';
import '../imports/api/rsvp/server/publications';
// import '/imports/api/timers/methods';
// import '/imports/api/timers/server/publications';
// import '/imports/api/tracks/methods';
// import '/imports/api/tracks/server/publications';
// import '/imports/api/user-options/server/publications';
// import '/imports/api/user-stats/server/publications';
// import '/imports/api/visualizers/server/publications';
import '../imports/startup/server';
// import '/imports/api/visualizers/methods';
import '/imports/api/users/methods';
import '../imports/api/users/server/publications.js';
// import '/imports/api/invites/methods';
// import '/imports/api/feedback/methods';
// import '/imports/api/fields/methods';
import '../imports/api/files/files';
import '../imports/api/files/methods';
import '../imports/api/admin/methods';
import '../imports/api/shares/methods';
import '../imports/api/subscriptions/methods';
import '../imports/api/apollo/server.js';
